# Site settings
title: ADHD Basic
email: mcvoid@mcvoid.org
description: >
  Basic Rules Variant for Fifth Edition Fantasy Roleplaying
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mcvoid.github.io" # the base hostname & protocol for your site
github_username:  mcvoid

# Build settings
markdown: kramdown
