# Site settings
title: Sean Wolcott's page
email: mcvoid@mcvoid.org
description: >
  Sean's projects and stuff.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mcvoid.github.io" # the base hostname & protocol for your site
github_username:  mcvoid

# Build settings
markdown: kramdown
