baseURL: 'http://mcvoid.org/'
languageCode: 'en-us'
title: 'mcvoid.org'
theme:
- mcvoid.org

# Needed for mermaid/katex shortcodes
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 1

# Multi-lingual mode config
# There are different options to translate files
# See https://gohugo.io/content-management/multilingual/#translation-by-filename
# And https://gohugo.io/content-management/multilingual/#translation-by-content-directory
languages:
  en:
    languageName: English
    contentDir: content
    weight: 1

# menu:
#   before: []
#   after:
#     - name: "Scape RPG"
#       url: "/scape"
#       weight: 10
#     - name: "Thievery! RPG"
#       url: "/thievery"
#       weight: 10
#       weight: 10
#     - name: "Blog"
#       url: "/blog"
#       weight: 10


params:

